services:
  catfish-tracker:
    image: ghcr.io/softwaresteph/wisdom-of-the-masses:latest
    ports:
      - "3000:3000"
    restart: unless-stopped
    environment:
      - APP_PATH=/catfish-tracker
    volumes:
      - catfish-data:/data
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  catfish-data:
    driver: local
