services:
  catfish-tracker:
    image: node:20-alpine
    ports:
      - "47822:3000"
    restart: unless-stopped
    environment:
      - SERVER_URL=/catfish-tracker/api
      #- PORT=3000
      #- DATA_DIR=/data
    volumes:
      - catfish-data:/data
    command: >
      sh -c "apk add --no-cache git &&
             rm -rf /repo && git clone -b feature/server-persistence https://github.com/softwaresteph/wisdom-of-the-masses /repo &&
             cd /repo && npm install --omit=dev &&
             node server.js"

volumes:
  catfish-data:
    driver: local
