services:
  catfish-tracker:
    image: ghcr.io/softwaresteph/wisdom-of-the-masses:latest
    ports:
      - "3000:3000"
    restart: unless-stopped
    volumes:
      - catfish-data:/data

volumes:
  catfish-data:
    driver: local
